version: '3'
services:
  netdata:
    image: netdata/netdata:v1.19.0
    hostname: mynode.local # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /opt/mynode/netdata/netdata.conf:/etc/netdata/netdata.conf:ro